/**
 * serviceMap.js
 * Maps pattern IDs → service metadata and remediation guidance
 */

'use strict';

const SERVICE_MAP = {
  aws_access_key: {
    service: 'Amazon Web Services',
    category: 'Cloud Provider',
    icon: '☁️',
    remediation: [
      'Immediately revoke the exposed key in AWS IAM console',
      'Review CloudTrail logs for unauthorized usage',
      'Rotate all credentials in the affected account',
      'Enable AWS Config rules to detect future key exposures',
      'Use IAM Roles instead of long-lived access keys',
    ],
    impact: 'Full AWS account access — can create/destroy resources, exfiltrate data, incur costs',
    cweId: 'CWE-798',
  },
  aws_secret_key: {
    service: 'Amazon Web Services',
    category: 'Cloud Provider',
    icon: '☁️',
    remediation: [
      'Revoke the Access Key ID + Secret pair immediately',
      'Audit IAM role permissions for least-privilege',
      'Enable GuardDuty for anomaly detection',
    ],
    impact: 'AWS secret key allows signing API requests — full account compromise possible',
    cweId: 'CWE-798',
  },
  google_api_key: {
    service: 'Google Cloud Platform',
    category: 'Cloud Provider',
    icon: '🔵',
    remediation: [
      'Restrict the API key to specific APIs and referrer domains in Google Cloud Console',
      'Delete the exposed key and generate a new restricted one',
      'Enable audit logging for API key usage',
      'Implement API key quotas and alerts',
    ],
    impact: 'Unauthorized API usage can lead to data exposure, billing abuse, or service disruption',
    cweId: 'CWE-798',
  },
  google_oauth: {
    service: 'Google OAuth',
    category: 'Authentication',
    icon: '🔵',
    remediation: [
      'Rotate the OAuth client secret in Google Cloud Console',
      'Restrict allowed redirect URIs',
      'Review authorized applications',
    ],
    impact: 'Can be used to impersonate the application in OAuth flows',
    cweId: 'CWE-287',
  },
  google_service_account: {
    service: 'Google Cloud Service Account',
    category: 'Cloud Provider',
    icon: '🔵',
    remediation: [
      'Immediately disable the service account key in IAM console',
      'Review audit logs for unauthorized usage',
      'Use Workload Identity Federation instead of service account keys',
      'Never store service account JSON in source code',
    ],
    impact: 'Service account keys have persistent access — can compromise GCP project',
    cweId: 'CWE-321',
  },
  firebase_key: {
    service: 'Google Firebase',
    category: 'BaaS',
    icon: '🔥',
    remediation: [
      'Add Firebase Security Rules to restrict database/storage access',
      'Enable Firebase App Check',
      'Restrict the API key to your domain in Google Cloud Console',
      'Review Firebase console for unauthorized data access',
    ],
    impact: 'Exposed Firebase keys can allow unauthorized read/write to Firestore, Storage, Auth',
    cweId: 'CWE-798',
  },
  stripe_live_secret: {
    service: 'Stripe',
    category: 'Payment Processor',
    icon: '💳',
    remediation: [
      'Immediately roll the key in Stripe Dashboard → API Keys',
      'Review payment logs for unauthorized charges or refunds',
      'Enable Stripe Radar rules',
      'Notify your security team and consider legal/compliance review',
      'Use Stripe Restricted Keys with minimal permissions',
    ],
    impact: 'CRITICAL — Full access to payment processing. Can charge cards, issue refunds, access customer PII',
    cweId: 'CWE-798',
  },
  stripe_test_secret: {
    service: 'Stripe (Test Mode)',
    category: 'Payment Processor',
    icon: '💳',
    remediation: [
      'Roll the test key in Stripe Dashboard',
      'Ensure production keys are never in client-side code',
      'Separate test/production environment configs',
    ],
    impact: 'Test key only — no real payment risk, but indicates poor secret management practices',
    cweId: 'CWE-798',
  },
  stripe_publishable: {
    service: 'Stripe (Publishable Key)',
    category: 'Payment Processor',
    icon: '💳',
    remediation: [
      'Publishable keys are designed to be public — no immediate action needed',
      'Restrict allowed domains in Stripe Dashboard',
    ],
    impact: 'Low — publishable keys are intended for client-side use',
    cweId: null,
  },
  github_pat: {
    service: 'GitHub',
    category: 'SCM / DevOps',
    icon: '🐙',
    remediation: [
      'Immediately revoke the token at github.com/settings/tokens',
      'Review audit log for repository access and actions performed',
      'Enable secret scanning in GitHub Advanced Security',
      'Use GitHub Apps instead of personal tokens for automation',
    ],
    impact: 'Can access, clone, or modify repositories — potential full codebase exposure',
    cweId: 'CWE-798',
  },
  github_oauth: {
    service: 'GitHub OAuth',
    category: 'SCM / DevOps',
    icon: '🐙',
    remediation: [
      'Revoke OAuth token in GitHub account settings',
      'Review authorized OAuth app permissions',
    ],
    impact: 'Access to GitHub resources depending on OAuth scopes granted',
    cweId: 'CWE-287',
  },
  github_app_token: {
    service: 'GitHub App',
    category: 'SCM / DevOps',
    icon: '🐙',
    remediation: [
      'GitHub App installation tokens expire after 1 hour — monitor for misuse',
      'Review GitHub App permissions and installation scope',
    ],
    impact: 'Short-lived token — repository access depending on app permissions',
    cweId: 'CWE-798',
  },
  slack_bot_token: {
    service: 'Slack',
    category: 'Communication',
    icon: '💬',
    remediation: [
      'Revoke the token in Slack API → Your Apps → OAuth & Permissions',
      'Review Slack audit logs for message access',
      'Re-install the Slack app to generate a new token',
    ],
    impact: 'Can read/write messages, access channels, and retrieve user data',
    cweId: 'CWE-798',
  },
  slack_user_token: {
    service: 'Slack (User)',
    category: 'Communication',
    icon: '💬',
    remediation: [
      'Revoke token in Slack account settings',
      'Review all Slack messages and files for sensitive data',
    ],
    impact: 'Full access to the user account — DMs, channels, files',
    cweId: 'CWE-798',
  },
  slack_webhook: {
    service: 'Slack Incoming Webhook',
    category: 'Communication',
    icon: '💬',
    remediation: [
      'Delete the webhook in Slack App settings and create a new one',
      'Restrict webhook URL exposure in source code',
    ],
    impact: 'Can send arbitrary messages to the connected Slack channel',
    cweId: 'CWE-798',
  },
  twilio_account_sid: {
    service: 'Twilio',
    category: 'Telephony / SMS',
    icon: '📞',
    remediation: [
      'Rotate credentials in Twilio Console → Account → API Keys',
      'Review call/SMS logs for unauthorized usage',
      'Set up usage alerts in Twilio console',
    ],
    impact: 'Can make calls, send SMS messages, and run up billing charges',
    cweId: 'CWE-798',
  },
  sendgrid_api_key: {
    service: 'SendGrid / Twilio SendGrid',
    category: 'Email',
    icon: '📧',
    remediation: [
      'Delete the API key in SendGrid Dashboard → Settings → API Keys',
      'Review email send logs for unauthorized messages',
      'Create a new restricted key with minimal permissions',
    ],
    impact: 'Can send unlimited phishing or spam emails from your domain',
    cweId: 'CWE-798',
  },
  mailgun_api_key: {
    service: 'Mailgun',
    category: 'Email',
    icon: '📧',
    remediation: [
      'Reset the API key in Mailgun Dashboard → Settings → API Keys',
      'Review email logs for unauthorized activity',
    ],
    impact: 'Can send emails, access email logs, and abuse your sending domain',
    cweId: 'CWE-798',
  },
  shopify_token: {
    service: 'Shopify',
    category: 'E-Commerce',
    icon: '🛍️',
    remediation: [
      'Revoke the access token in Shopify Partner Dashboard',
      'Review order and customer data for unauthorized access',
      'Audit installed apps and their permissions',
    ],
    impact: 'Access to store orders, customers, products, and potentially payment info',
    cweId: 'CWE-798',
  },
  jwt_token: {
    service: 'JWT Token',
    category: 'Authentication',
    icon: '🔑',
    remediation: [
      'Rotate signing secrets used to issue JWTs',
      'Implement short expiry times and token rotation',
      'Validate JWT audience and issuer claims strictly',
      'Never store sensitive data in JWT payload (it is only Base64-encoded, not encrypted)',
    ],
    impact: 'Exposed JWT may allow session hijacking or privilege escalation depending on claims',
    cweId: 'CWE-347',
  },
  mongodb_uri: {
    service: 'MongoDB',
    category: 'Database',
    icon: '🗄️',
    remediation: [
      'Immediately rotate MongoDB credentials',
      'Enable MongoDB Atlas IP Access Lists',
      'Audit database access logs',
      'Never store connection strings in source code — use environment variables',
    ],
    impact: 'CRITICAL — Full database read/write access. Potential data breach or ransomware attack',
    cweId: 'CWE-312',
  },
  postgres_uri: {
    service: 'PostgreSQL',
    category: 'Database',
    icon: '🗄️',
    remediation: [
      'Rotate database credentials immediately',
      'Restrict pg_hba.conf to known IPs',
      'Enable SSL for database connections',
      'Use connection pooling (PgBouncer) with limited credentials',
    ],
    impact: 'CRITICAL — Full database access',
    cweId: 'CWE-312',
  },
  azure_storage_key: {
    service: 'Azure Storage',
    category: 'Cloud Provider',
    icon: '🔷',
    remediation: [
      'Rotate storage account keys in Azure Portal',
      'Use SAS tokens with expiry instead of account keys',
      'Enable Azure Storage logging to review access',
    ],
    impact: 'Full access to Azure Blob Storage, Tables, Queues, and Files',
    cweId: 'CWE-798',
  },
  generic_api_key: {
    service: 'Unknown API',
    category: 'Generic',
    icon: '🔐',
    remediation: [
      'Identify the service this key belongs to',
      'Rotate the key in the corresponding service dashboard',
      'Move all secrets to environment variables or a secrets manager (HashiCorp Vault, AWS Secrets Manager)',
    ],
    impact: 'Unknown — depends on the service',
    cweId: 'CWE-798',
  },
  generic_bearer_token: {
    service: 'Bearer Token',
    category: 'Authentication',
    icon: '🔑',
    remediation: [
      'Revoke the token in the issuing service',
      'Implement short-lived tokens with refresh rotation',
    ],
    impact: 'API authentication bypass for the associated service',
    cweId: 'CWE-798',
  },
  entropy_heuristic: {
    service: 'Entropy Detection (Unclassified)',
    category: 'Heuristic',
    icon: '🎲',
    remediation: [
      'Manually verify whether this string is a secret',
      'If confirmed as a secret, identify the service and rotate it',
      'Move to environment variable / secrets manager',
    ],
    impact: 'Unknown — requires manual investigation',
    cweId: null,
  },
};

module.exports = { SERVICE_MAP };
